apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coda-backend
  namespace: coda-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - coda.heybanco.mx
    secretName: coda-tls
  rules:
  - host: coda.heybanco.mx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coda-backend
            port:
              number: 80
