apiVersion: v1
kind: Service
metadata:
  name: coda-backend
  namespace: coda-prod
  labels:
    app: coda-backend
spec:
  type: ClusterIP
  selector:
    app: coda-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
